// src/utils/mockData.js - Mock building data for development/testing
// Use this when the backend API is not available

export const mockBuildings = [
  {
    building_id: 1,
    building_name: 'Main Administration Building',
    building_code: 'ADMIN',
    latitude: '11.2443',
    longitude: '125.0023',
    description: 'Main administrative offices and student services center.',
    category: 'administrative',
    width_meters: 30,
    height_meters: 25,
    rotation_degrees: 0,
  },
  {
    building_id: 2,
    building_name: 'Library Building',
    building_code: 'LIB',
    latitude: '11.2450',
    longitude: '125.0030',
    description: 'Central library with study areas and computer labs.',
    category: 'academic',
    width_meters: 35,
    height_meters: 20,
    rotation_degrees: 0,
  },
  {
    building_id: 3,
    building_name: 'Science Laboratory',
    building_code: 'SCI',
    latitude: '11.2435',
    longitude: '125.0015',
    description: 'Science laboratories and research facilities.',
    category: 'academic',
    width_meters: 25,
    height_meters: 20,
    rotation_degrees: 0,
  },
  {
    building_id: 4,
    building_name: 'Engineering Building',
    building_code: 'ENG',
    latitude: '11.2460',
    longitude: '125.0040',
    description: 'Engineering department with workshops and labs.',
    category: 'academic',
    width_meters: 40,
    height_meters: 30,
    rotation_degrees: 0,
  },
  {
    building_id: 5,
    building_name: 'Cafeteria',
    building_code: 'CAFE',
    latitude: '11.2440',
    longitude: '125.0025',
    description: 'Student cafeteria and dining area.',
    category: 'facilities',
    width_meters: 20,
    height_meters: 15,
    rotation_degrees: 0,
  },
  {
    building_id: 6,
    building_name: 'Gymnasium',
    building_code: 'GYM',
    latitude: '11.2470',
    longitude: '125.0035',
    description: 'Sports and recreation facility.',
    category: 'facilities',
    width_meters: 50,
    height_meters: 35,
    rotation_degrees: 0,
  },
];

